apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy1
  name: reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy1
